### ISSUE TITLE
package canvas won't install

### ISSUE THREAD

**Issue by JessyBorcard** [CPNV-RIA1/imagitor#1]
the canvas package can't be installed, even after following canvas' doc, 

even after following this
![657578](https://user-images.githubusercontent.com/48352287/227146586-b0334de5-8cc7-47f6-874c-676d405d51bd.PNG)

i still get a huge error, first lines of the error i get
![43535](https://user-images.githubusercontent.com/48352287/227147321-e4f5a04e-213c-4c38-a853-5c00e115a074.PNG)

npm version : 8.19.2
node version : 18.3.0

**Comment by YannickPerret** [comment]
Après test sur un autre pc, il n'y a pas de bug dans l'installation de la librairie Canvas.

**Comment by JessyBorcard** [comment]
needed to download the optional library in the install doc
